version: 2

multi-ecosystem-groups:
  rust-crates:
    schedule:
      interval: "weekly"

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "rust-crates"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/python"
    patterns: ["*"]
    multi-ecosystem-group: "rust-crates"
  - package-ecosystem: "cargo"
    directory: "/cli"
    patterns: ["*"]
    multi-ecosystem-group: "rust-crates"
